enableConstraintsChecks: true

enableHardenedMode: true

enableInlineHunks: true

nodeLinker: node-modules

npmScopes:
  msmall2691-eng:
    npmAlwaysAuth: true
    npmAuthToken: ${GITHUB_TOKEN-}
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.13.0.cjs
